import { GuidePage } from "../guide-page";

export default function PhoneGuide() {
  return <GuidePage eyebrow="GUÍA DE TELEFONÍA" title="Preparar llamadas desde GoHighLevel" intro="Esta guía ayuda a elegir una configuración telefónica y a conocer sus implicaciones. No compra números, no realiza llamadas y no activa grabaciones." provider="GoHighLevel" officialUrl="https://help.gohighlevel.com/support/solutions/articles/48001229976-phone-number-settings-explained" steps={[
    { title: "Define para qué usarás la telefonía", text: "Indica si necesitas llamadas salientes, llamadas entrantes y salientes, seguimiento comercial o simplemente registrar tareas manuales.", visual: ["Objetivo", "Salientes / Entrantes", "Responsable"], checklist: ["Países desde los que se llamará.", "Países de los clientes.", "Horario y responsables."] },
    { title: "Elige la ruta del número", text: "Para un sistema telefónico completo suele utilizarse un número contratado o portado a GoHighLevel. La documentación actual también contempla verificar un número existente para determinadas llamadas salientes, sujeto a compatibilidad.", visual: ["Comprar o portar", "Número existente verificado", "Revisar compatibilidad"], warning: "No se garantiza que un número existente sirva para todas las funciones. Focus Business debe comprobar disponibilidad, país y funciones antes de activarlo." },
    { title: "Revisa disponibilidad y coste", text: "La disponibilidad y el precio dependen del país, tipo de número y proveedor de telefonía. Puede haber alquiler del número, consumo por llamadas, grabación y otros cargos.", visual: ["País y tipo de número", "Coste vigente", "Aprobación antes de comprar"], checklist: ["No se compra nada desde este formulario.", "Los importes se confirman dentro de la plataforma.", "La empresa aprueba el coste antes de activar."] },
    { title: "Abre el sistema telefónico", text: "En la subcuenta de GoHighLevel entra en Settings, Phone System y Phone Numbers. Confirma que estás en la subcuenta correcta.", visual: ["Settings", "Phone System", "Phone Numbers"], checklist: ["No uses una subcuenta de otro cliente.", "Comprueba país y prefijo antes de continuar."] },
    { title: "Configura el enrutamiento", text: "Define quién recibe las llamadas, qué ocurre si no responde y si debe ir a buzón, otro usuario o un número externo.", visual: ["Número", "Forward Calls To", "Timeout / Voicemail"], checklist: ["Responsable principal y respaldo.", "Horario de atención.", "Mensaje de llamada perdida."] },
    { title: "Revisa el número que verá el cliente", text: "Si se desea mostrar un número local existente, debe verificarse como identificador permitido y probarse. La disponibilidad varía por país y operador.", visual: ["Caller ID", "Verificar número", "Llamada de prueba"], warning: "Nunca suplantes un número. Utiliza únicamente números propiedad de la empresa y autorizados por el proveedor." },
    { title: "Decide sobre la grabación", text: "La grabación puede generar coste y obligaciones legales. Define si se activará, qué aviso recibirá la persona y cuánto tiempo se conservará.", visual: ["Call Recording", "Aviso de grabación", "Retención"], checklist: ["Revisar la normativa de los países implicados.", "Informar u obtener consentimiento cuando corresponda.", "Limitar acceso a las grabaciones."] },
    { title: "Realiza una prueba controlada", text: "Tras la configuración y aprobación del coste, realiza una llamada de prueba para validar audio, número visible, enrutamiento, aviso y registro en el CRM.", visual: ["Llamada de prueba", "Número visible", "Registro correcto"], checklist: ["No llames a clientes durante la prueba.", "Documenta el resultado y corrige antes de activar al equipo."] },
  ]} />;
}
