import { GuidePage } from "../guide-page";

export default function AdsManagerGuide() {
  return <GuidePage eyebrow="GUÍA 3 DE 3" title="Dar acceso al Administrador de anuncios" intro="La cuenta publicitaria, sus permisos y su facturación se administran por separado. La empresa introduce el método de pago directamente en Meta." provider="Meta" officialUrl="https://www.facebook.com/help/messenger-app/195296697183682/" steps={[
    { title: "Identifica la cuenta correcta", text: "Antes de asignar acceso, anota el nombre e identificador de la cuenta publicitaria, la moneda y la zona horaria. Estos datos no suelen poder cambiarse libremente después.", visual: ["Cuenta publicitaria", "ID · moneda · zona horaria", "Confirmar"], checklist: ["No uses una cuenta personal o de otro negocio.", "Comprueba que la cuenta no esté restringida."] },
    { title: "Abre Cuentas publicitarias", text: "En Configuración del negocio entra en Cuentas, después Cuentas publicitarias y selecciona la cuenta correcta en la columna central.", visual: ["Configuración del negocio", "Cuentas publicitarias", "Cuenta seleccionada"], checklist: ["Si no aparece, revisa el portafolio seleccionado.", "No solicites propiedad de una cuenta ajena sin confirmación."] },
    { title: "Elige Asignar personas", text: "Pulsa Añadir personas o Asignar personas. Si la persona aún no aparece, completa primero la guía de Meta Business Suite.", visual: ["Asignar personas", "Persona confirmada", "Permisos"], checklist: ["Evita duplicar usuarios.", "Usa la identidad enviada por Focus Business."] },
    { title: "Concede el nivel necesario", text: "Durante la configuración puede requerirse acceso administrativo para revisar activos, conversiones, facturación y permisos. Actívalo solo para la persona confirmada.", visual: ["Permisos", "Administrar campañas", "Administrar cuenta"], warning: "Un administrador puede editar permisos y métodos de pago. Revisa y reduce el acceso al terminar la implementación." },
    { title: "Comprueba los activos relacionados", text: "Verifica que la cuenta publicitaria tenga asociadas la página de Facebook, la cuenta de Instagram y las fuentes de datos que realmente correspondan.", visual: ["Activos conectados", "Página e Instagram", "Fuentes de datos"], checklist: ["No conectes activos de otros clientes.", "No crees píxeles o conversiones desde esta guía."] },
    { title: "Abre Facturación y pagos", text: "En el Administrador de anuncios entra en Facturación y pagos y después Configuración de pagos. Selecciona siempre la misma cuenta publicitaria.", visual: ["Facturación y pagos", "Configuración de pagos", "Cuenta correcta"], checklist: ["Confirma el país, moneda y titular.", "No envíes datos financieros por correo o formulario."] },
    { title: "Añade el método de pago", text: "Pulsa Añadir método de pago y completa los datos directamente en la interfaz oficial de Meta. Focus Business no necesita ver ni guardar la tarjeta.", visual: ["Métodos de pago", "Añadir método", "Guardar en Meta"], warning: "Meta indica que debes ser administrador de la cuenta publicitaria para añadir o modificar el método de pago." },
    { title: "Revisa acceso y facturación", text: "Confirma que la persona aparece con el permiso acordado y que el método de pago figura disponible. No publiques campañas ni establezcas presupuesto desde esta guía.", visual: ["Personas", "Método disponible", "Sin campañas activadas"], checklist: ["La inversión publicitaria requiere una aprobación aparte.", "Reduce o retira permisos cuando termine la configuración."] },
  ]}><div className="guide-alert payment"><b>Importante</b><span>Meta indica que debes ser administrador de la cuenta publicitaria para añadir o editar el método de pago.</span></div></GuidePage>;
}
