"use client";
import { FormEvent, useState } from "react";

const accessEmails = ["demo@luznorte.es", "servicemanagerbossio@gmail.com"];
const sections = [
  ["Empresa e identidad", [["Empresa", "Luz Norte Producciones"], ["Razón social", "Luz Norte Producciones S.L."], ["Web", "luznorteproducciones.es"], ["Actividad", "Productora audiovisual"], ["Sede", "Madrid, España"], ["Equipo", "6–10 personas"], ["Tono", "Profesional"]]],
  ["Oferta y público", [["Servicio prioritario", "Vídeo corporativo y campañas B2B"], ["Ticket medio", "8.000–20.000 €"], ["Modelo", "Presupuesto personalizado"], ["Servicios", "Vídeo corporativo, contenido para redes, motion graphics"], ["Público", "B2B"], ["Sectores", "Tecnología, industria y salud"], ["Mercados", "España y Portugal"], ["Decisor", "Dirección de marketing"]]],
  ["Captación y proceso comercial", [["Objetivos", "Aumentar reuniones, captar clientes B2B, automatizar seguimiento"], ["Canales", "LinkedIn, email outbound, formulario web, referidos"], ["Datos del lead", "Nombre, empresa, email, teléfono, presupuesto y fecha prevista"], ["Tiempo de respuesta", "15 minutos"], ["Asignación", "Ronda (round robin)"], ["Ciclo de venta", "3–6 semanas"], ["Lead cualificado", "Necesidad real, decisor identificado y proyecto previsto en 90 días."]]],
  ["Equipo y comunicación", [["Responsable", "Laura Martínez · Dirección comercial"], ["Correo", "laura@luznorteproducciones.es"], ["WhatsApp", "+34 600 123 456"], ["Reunión", "Diagnóstico inicial · 45 minutos"], ["Disponibilidad", "Lunes–viernes, 09:00–18:00"], ["Tratamiento", "Usted"], ["Tono", "Profesional"]]],
  ["Automatizaciones", [["Flujos", "Confirmación de lead, aviso interno, asignación automática, seguimiento de propuesta"], ["Integraciones", "Google Calendar, Gmail, WhatsApp, Google Sheets"], ["Cuenta GoHighLevel", "No"], ["Lanzamiento", "15/09/2026"], ["Aprobación", "Laura Martínez"]]],
];

export default function PortalDemoPage() {
  const [email, setEmail] = useState("");
  const [allowed, setAllowed] = useState(false);
  const [error, setError] = useState(false);
  const [open, setOpen] = useState(false);
  function enter(event: FormEvent) { event.preventDefault(); const ok = accessEmails.includes(email.trim().toLowerCase()); setAllowed(ok); setError(!ok); }
  if (!allowed) return <main className="portal access"><section className="access-card"><a className="brand" href="/"><i>F</i><span>FOCUS<small>BUSINESS</small></span></a><p className="eyebrow">PORTAL DE CONFIGURACIÓN</p><h1>Accede con tu correo</h1><p className="intro">Introduce el correo autorizado para consultar las configuraciones de productoras.</p><form onSubmit={enter}><label className="input"><span>Correo electrónico</span><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="nombre@empresa.com" autoFocus required /></label><button className="primary access-button">Continuar →</button></form>{error && <p className="access-error">Este correo no está activo. Usa un correo marcado como <b>Activo</b> en la hoja de accesos.</p>}<p className="access-note">En la versión operativa se validará automáticamente el estado <b>Activo</b> de Google Sheets.</p></section></main>;
  return <main className="portal"><header className="portal-header"><a className="brand" href="/"><i>F</i><span>FOCUS<small>BUSINESS</small></span></a><div className="viewer"><span>{email}</span><small>Administrador de demostración</small><button className="link-button" onClick={() => { setAllowed(false); setOpen(false); }}>Salir</button></div></header><section className="portal-body"><p className="eyebrow">PORTAL DE CONFIGURACIÓN</p><h1>Productoras registradas</h1><p className="intro">Pulsa una productora para abrir la ficha completa y revisar todos los datos antes de crear su cuenta de GoHighLevel.</p><div className="portal-stats"><div><b>1</b><span>Registro recibido</span></div><div><b>1</b><span>Listo para GHL</span></div><div><b>Administrador</b><span>Rol de prueba</span></div></div><button type="button" className="record record-button" onClick={() => setOpen(!open)}><div><p className="record-id">ONB-DEMO-2026</p><h2>Luz Norte Producciones</h2><p>Vídeo corporativo y campañas B2B · Tecnología, industria y salud</p></div><div className="record-meta"><span className="tag">Listo para GHL</span><span>laura@luznorteproducciones.es</span><span>{open ? "Cerrar ficha ↑" : "Ver ficha completa →"}</span></div></button>{open && <div className="detail-card"><div className="detail-heading"><div><p className="eyebrow">FICHA COMPLETA</p><h2>Luz Norte Producciones</h2></div><span className="tag">Listo para GHL</span></div>{sections.map(([title, fields]) => <section className="detail-section" key={title as string}><h3>{title as string}</h3><div className="detail-grid">{(fields as string[][]).map(([label, value]) => <div key={label}><b>{label}</b><span>{value}</span></div>)}</div></section>)}<div className="detail-actions"><button className="primary" type="button">Descargar JSON para Codex</button><button className="secondary" type="button">Marcar como subcuenta creada</button></div></div>}</section></main>;
}
