"use client";
import { useEffect, useState } from "react";

type RecordRow = Record<string, string | boolean>;
type PortalResponse = { ok: boolean; role?: string; records?: RecordRow[]; error?: string; configured?: boolean };

export default function PortalClient({ user }: { user: { email: string; name: string } }) {
  const [data, setData] = useState<PortalResponse | null>(null);
  useEffect(() => { fetch("/api/portal").then((r) => r.json()).then(setData).catch(() => setData({ ok: false, error: "No se pudo cargar la información." })); }, []);
  const records = data?.records ?? [];
  return <main className="portal"><header className="portal-header"><a className="brand" href="/"><i>F</i><span>FOCUS<small>BUSINESS</small></span></a><div className="viewer"><span>{user.name}</span><small>{user.email}</small><a href="/signout-with-chatgpt?return_to=/">Salir</a></div></header><section className="portal-body"><p className="eyebrow">PORTAL DE CONFIGURACIÓN</p><h1>Productoras registradas</h1><p className="intro">Consulta la información enviada y prepara la creación de cada subcuenta de GoHighLevel.</p>{!data && <div className="portal-state">Cargando registros…</div>}{data && !data.ok && <div className="portal-state error">{data.configured === false ? "El portal está protegido, pero falta conectar el lector seguro de Google Sheets." : data.error || "No tienes acceso a este portal."}</div>}{data?.ok && <><div className="portal-stats"><div><b>{records.length}</b><span>Registros recibidos</span></div><div><b>{records.filter((row) => row["Estado"] === "Listo para GHL").length}</b><span>Listos para GHL</span></div><div><b>{data.role}</b><span>Tu rol</span></div></div><div className="record-list">{records.length === 0 ? <div className="portal-state">Aún no hay formularios enviados.</div> : records.map((row, index) => <article className="record" key={`${String(row["ID registro"])}-${index}`}><div><p className="record-id">{String(row["ID registro"] || "Nuevo registro")}</p><h2>{String(row["Empresa"] || "Empresa sin nombre")}</h2><p>{String(row["Servicio prioritario"] || "Servicio pendiente")} · {String(row["Público"] || "Público pendiente")}</p></div><div className="record-meta"><span className={row["Estado"] === "Activo" ? "tag active" : "tag"}>{String(row["Estado"] || "Nuevo")}</span><span>{String(row["Email responsable"] || "Sin correo")}</span><span>{String(row["Fecha lanzamiento"] || "Sin fecha")}</span></div></article>)}</div></>}</section></main>;
}
