"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type RecordRow = Record<string, string | boolean>;
type PortalResponse = { ok: boolean; role?: string; records?: RecordRow[]; error?: string; configured?: boolean };

export default function PortalClient({ user }: { user: { email: string; name: string } }) {
  const [data, setData] = useState<PortalResponse | null>(null);
  const [selected, setSelected] = useState<RecordRow | null>(null);
  useEffect(() => { fetch("/api/portal").then((r) => r.json()).then(setData).catch(() => setData({ ok: false, error: "No se pudo cargar la información." })); }, []);
  const records = data?.records ?? [];
  const selectedFields = selected ? Object.entries(selected).filter(([, value]) => String(value ?? "").trim() !== "") : [];
  return <main className="portal"><header className="portal-header"><Link className="brand" href="/"><i>F</i><span>FOCUS<small>BUSINESS</small></span></Link><div className="viewer"><span>{user.name}</span><small>{user.email}</small><a href="/signout-with-chatgpt?return_to=/">Salir</a></div></header><section className="portal-body"><p className="eyebrow">PORTAL DE CONFIGURACIÓN</p><h1>Productoras registradas</h1><p className="intro">Consulta la información enviada y abre cada registro para revisar todos sus datos.</p>{!data && <div className="portal-state">Cargando registros…</div>}{data && !data.ok && <div className="portal-state error">{data.configured === false ? "El portal está protegido, pero falta conectar el lector seguro de Google Sheets." : data.error || "No tienes acceso a este portal."}</div>}{data?.ok && <><div className="portal-stats"><div><b>{records.length}</b><span>Registros recibidos</span></div><div><b>{records.filter((row) => row["Estado"] === "Listo para GHL").length}</b><span>Listos para GHL</span></div><div><b>{data.role}</b><span>Tu rol</span></div></div><div className="record-list">{records.length === 0 ? <div className="portal-state">Aún no hay formularios enviados.<br /><Link className="primary" href="/">Abrir formulario de registro →</Link></div> : records.map((row, index) => <button type="button" className="record record-button" key={`${String(row["ID registro"])}-${index}`} onClick={() => setSelected(row)}><div><p className="record-id">{String(row["ID registro"] || "Nuevo registro")}</p><h2>{String(row["Empresa"] || "Empresa sin nombre")}</h2><p>{String(row["Servicio prioritario"] || "Servicio pendiente")} · {String(row["Público"] || "Público pendiente")}</p></div><div className="record-meta"><span className={row["Estado"] === "Activo" ? "tag active" : "tag"}>{String(row["Estado"] || "Nuevo")}</span><span>{String(row["Email responsable"] || "Sin correo")}</span><span>{String(row["Fecha lanzamiento"] || "Sin fecha")}</span></div></button>)}</div>{selected && <section className="detail-card"><div className="detail-heading"><div><p className="eyebrow">FICHA COMPLETA</p><h2>{String(selected["Empresa"] || "Registro")}</h2></div><button type="button" className="secondary" onClick={() => setSelected(null)}>Cerrar</button></div><div className="detail-section"><div className="detail-grid">{selectedFields.map(([label, value]) => <div key={label}><b>{label}</b><span>{String(value)}</span></div>)}</div></div></section>}</>}</section></main>;
}
