import { GuidePage } from "../guide-page";

export default function MetaBusinessGuide() {
  return <GuidePage eyebrow="GUÍA 1 DE 3" title="Dar acceso a Meta Business Suite" intro="Esta guía permite preparar el portafolio empresarial correcto sin compartir la contraseña de Facebook. Completa también las guías de página y cuenta publicitaria: son permisos distintos." provider="Meta" officialUrl="https://www.facebook.com/help/187316341316631" steps={[
    { title: "Prepara los datos correctos", text: "Antes de entrar, confirma el nombre del portafolio empresarial, la página y la cuenta publicitaria que se configurarán.", visual: ["Nombre del negocio", "Página de Facebook", "Cuenta publicitaria"], checklist: ["Entra con tu perfil personal autorizado.", "Ten a mano el nombre o correo que te enviará Focus Business.", "No envíes contraseñas ni códigos de seguridad."] },
    { title: "Abre la configuración del negocio", text: "En Meta Business Suite abre Configuración. Si ves varios negocios, usa el selector superior para elegir el portafolio correcto antes de continuar.", visual: ["Meta Business Suite", "Configuración", "Portafolio seleccionado"], checklist: ["Comprueba el nombre y el identificador del negocio.", "No trabajes sobre un negocio de otra empresa."] },
    { title: "Entra en Personas", text: "Dentro de Configuración del negocio, abre Usuarios y después Personas. Allí verás quién tiene acceso actualmente.", visual: ["Usuarios", "Personas", "Añadir"], checklist: ["Revisa que no exista ya una invitación pendiente para la misma persona.", "Si ya existe, no la dupliques: informa a Focus Business."] },
    { title: "Añade a la persona confirmada", text: "Pulsa Añadir e introduce únicamente la dirección que Focus Business te haya confirmado por un canal directo. Revisa cada letra antes de continuar.", visual: ["Añadir persona", "Correo confirmado", "Siguiente"], warning: "No uses un correo parecido ni uno que aparezca en una captura antigua." },
    { title: "Asigna los activos necesarios", text: "Selecciona solo los activos de esta empresa: página, cuenta de Instagram si aplica y cuenta publicitaria. La página y la cuenta de anuncios se validan además en sus guías específicas.", visual: ["Asignar activos", "Página · Instagram · Anuncios", "Permisos"], checklist: ["No selecciones activos personales o de otros clientes.", "Comprueba el nombre e identificador de cada activo."] },
    { title: "Concede acceso durante la configuración", text: "Si se requiere control total para configurar el sistema, actívalo solo para la persona confirmada y durante el periodo de implementación.", visual: ["Permisos", "Control total", "Confirmar"], warning: "El control total permite administrar configuraciones y accesos. Meta advierte que una persona con ese control puede cambiar permisos e incluso eliminar la página." },
    { title: "Envía y verifica la invitación", text: "Confirma el resumen, envía la invitación y comprueba que aparece como enviada o pendiente. La persona invitada debe aceptarla para que el acceso esté activo.", visual: ["Resumen", "Enviar invitación", "Pendiente / Activa"], checklist: ["Anota el negocio y activos incluidos.", "Si Meta solicita tu contraseña para confirmar, introdúcela solo en la interfaz oficial de Meta."] },
    { title: "Revisa los permisos al finalizar", text: "Cuando Focus Business confirme que la configuración terminó, vuelve a Personas y reduce o retira los permisos que ya no sean necesarios.", visual: ["Personas", "Editar acceso", "Reducir o retirar"], checklist: ["No retires acceso durante una configuración en curso.", "Conserva únicamente los permisos operativos acordados."] },
  ]} />;
}
