import { GuidePage } from "../guide-page";

export default function WhatsAppGuide() {
  return <GuidePage eyebrow="GUÍA DE WHATSAPP" title="Preparar WhatsApp Business en GoHighLevel" intro="La conexión se realiza mediante la integración oficial de WhatsApp Business Platform. Esta guía no conecta la cuenta, no envía mensajes y no solicita códigos." provider="GoHighLevel y Meta" officialUrl="https://help.gohighlevel.com/support/solutions/articles/155000006911-whatsapp-settings" steps={[
    { title: "Confirma que la empresa puede usar WhatsApp Business", text: "La empresa debe disponer de un negocio válido en Meta y aceptar las condiciones de WhatsApp Business. Define quién será responsable de la cuenta.", visual: ["Empresa", "Meta Business", "Responsable"], checklist: ["Nombre legal y comercial coherentes.", "Sitio web y datos de contacto públicos.", "Persona autorizada para realizar la conexión."] },
    { title: "Revisa el número que quieres utilizar", text: "El número debe pertenecer a la empresa y poder recibir el código de verificación. Un número que ya usa la app de WhatsApp puede requerir una ruta específica de coexistencia o migración, si está disponible para esa cuenta.", visual: ["Número empresarial", "Elegibilidad", "Coexistencia o migración"], warning: "No borres una cuenta ni desconectes un número existente antes de que GoHighLevel y Meta confirmen la ruta compatible." },
    { title: "Comprueba los costes vigentes", text: "GoHighLevel y WhatsApp pueden aplicar suscripción y cargos de mensajería según país, categoría y uso. Los importes se revisan en la plataforma antes de aprobar la conexión.", visual: ["Suscripción", "Mensajería", "Aprobación de coste"], checklist: ["No se cobra nada al enviar este formulario.", "No se inventan precios: se confirma el importe vigente.", "La empresa autoriza cualquier activación posterior."] },
    { title: "Abre la configuración de WhatsApp", text: "En la subcuenta correcta entra en Settings y después WhatsApp. Allí se inicia el proceso oficial de conexión.", visual: ["Settings", "WhatsApp", "Connect / Sign up with Facebook"], checklist: ["Confirma la subcuenta del cliente.", "No compartas la contraseña de Facebook o WhatsApp."] },
    { title: "Inicia sesión directamente en Meta", text: "La persona autorizada inicia sesión en la ventana oficial de Meta, selecciona el portafolio empresarial y la cuenta de WhatsApp Business correctos.", visual: ["Inicio de sesión de Meta", "Portafolio", "WhatsApp Business Account"], checklist: ["Comprueba el dominio oficial de Meta.", "No envíes códigos de doble factor a terceros."] },
    { title: "Verifica el perfil empresarial", text: "Revisa el nombre visible, categoría, descripción, sitio web y demás datos que aparecerán asociados al negocio.", visual: ["Business profile", "Nombre visible", "Datos de empresa"], checklist: ["El nombre debe representar a la empresa.", "No uses marcas o datos de otra entidad."] },
    { title: "Verifica el número", text: "Meta enviará un código por el método disponible. La persona propietaria lo introduce directamente en la ventana oficial para finalizar la verificación.", visual: ["Método de verificación", "Código en Meta", "Número conectado"], warning: "Focus Business nunca necesita recibir el código. No lo escribas en este formulario." },
    { title: "Revisa estado y realiza una prueba autorizada", text: "Cuando la plataforma muestre el número conectado, comprueba el estado, las plantillas y los límites. Una prueba real de mensaje requiere consentimiento y autorización aparte.", visual: ["Estado conectado", "Plantillas", "Prueba autorizada"], checklist: ["No actives automatizaciones durante la guía.", "Configura responsables y horarios antes de usar el canal.", "Documenta el coste y la aprobación."] },
  ]} />;
}
