import { GuidePage } from "../guide-page";

export default function FacebookPageGuide() {
  return <GuidePage eyebrow="GUÍA 2 DE 3" title="Dar acceso a la página de Facebook" intro="La página se revisa por separado para asegurar que la invitación del negocio incluya el activo correcto y el nivel de acceso necesario." provider="Meta" officialUrl="https://www.facebook.com/help/187316341316631" steps={[
    { title: "Comprueba tu propio acceso", text: "En Facebook abre tu foto de perfil, elige Ver todos los perfiles y cambia a la página que se configurará.", visual: ["Foto de perfil", "Ver todos los perfiles", "Página correcta"], checklist: ["Confirma el nombre y la imagen de la página.", "Necesitas control total para administrar el acceso de otras personas."] },
    { title: "Abre la configuración de la página", text: "Con la página activa, abre Configuración y privacidad y después Configuración. La ubicación del menú puede variar entre ordenador y móvil.", visual: ["Configuración y privacidad", "Configuración", "Página"], checklist: ["Hazlo desde una sesión personal autorizada.", "Evita menús de una página distinta."] },
    { title: "Localiza Acceso a la página", text: "En Configuración de la página busca Acceso a la página. Si la página pertenece a un portafolio empresarial, Meta puede redirigirte a Configuración del negocio.", visual: ["Configuración de la página", "Acceso a la página", "Personas con acceso"], checklist: ["Revisa quién tiene acceso de Facebook.", "Distingue acceso de Facebook de acceso para tareas."] },
    { title: "Pulsa Añadir nuevo", text: "En Personas con acceso de Facebook selecciona Añadir nuevo y continúa. Si Meta te lleva al negocio, vuelve a la guía de Meta Business Suite.", visual: ["Acceso de Facebook", "Añadir nuevo", "Siguiente"], warning: "No uses una opción de acceso parcial si impide la configuración acordada; revisa primero el alcance exacto con Focus Business." },
    { title: "Busca a la persona confirmada", text: "Introduce el nombre o correo que Focus Business te haya enviado de forma personal y comprueba la identidad antes de seleccionarla.", visual: ["Buscar persona", "Nombre o correo exacto", "Seleccionar"], checklist: ["Comprueba foto, nombre y correo cuando Meta los muestre.", "No continúes si la identidad no coincide."] },
    { title: "Revisa el control total", text: "Activa el nivel necesario para la configuración únicamente si fue acordado. Lee el aviso de Meta completo antes de confirmar.", visual: ["Permitir control total", "Revisar aviso", "Dar acceso"], warning: "El control total puede administrar contenido, mensajes, configuración, accesos y eliminar la página. Debe limitarse a la persona confirmada y al tiempo necesario." },
    { title: "Confirma de forma segura", text: "Meta puede pedir que confirmes con tu contraseña. Escríbela solo dentro de Facebook; nunca la envíes a Focus Business ni la pegues en el formulario.", visual: ["Confirmación de Meta", "Contraseña en Meta", "Enviar invitación"], checklist: ["Comprueba que la URL y la sesión son de Meta/Facebook.", "No compartas capturas con contraseñas o códigos."] },
    { title: "Verifica el resultado", text: "Comprueba que la persona aparece como invitada, pendiente o activa. Tras la implementación, revisa con Focus Business si debe mantenerse, reducirse o retirarse.", visual: ["Personas con acceso", "Pendiente / Activa", "Revisar al finalizar"], checklist: ["No dupliques invitaciones.", "Conserva evidencia del estado, no de las credenciales."] },
  ]} />;
}
